"use strict";
let snackServings = 1289;
let guests = 23;
console.log(snackServings, guests);
console.log(snackServings - guests);
console.log(guests - snackServings);
console.log(snackServings * guests);
console.log(snackServings / guests);
console.log(guests / snackServings);
let drink = "10";
let resultOne = (snackServings * guests) / drink;
console.log(resultOne);
let monkeys = 15;
let bananas = 9;
console.log(monkeys / bananas);
let monkeyfights = 20;
let resultTwo = (monkeys + bananas) * monkeyfights;
console.log(resultTwo);
console.log(++monkeys);
console.log(--bananas);
let happines = monkeys - bananas;
console.log(happines, monkeyfights);
console.log(resultOne % resultTwo);
